# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ready',
            field=models.BooleanField(default=True),
        ),
    ]
